Fix PIX random key regex
fiatconnect/fiatconnect-types pull request #111
Opened 2023-01-05 14:45 UTC by ailsoncgt

Random key accept dash characters .

2023-01-06 00:23 UTC, cajubelt requested changes

2023-01-06 00:23 UTC, cajubelt commented on src/fiat-account.ts
> +
```suggestion
```
looks like this was included by mistake

2023-01-11 00:23 UTC, cajubelt approved these changes

2023-01-11 00:26 UTC, satish-ravi approved these changes

2023-01-11 21:40 UTC, merged